version: "3.1"

services:
  server:
    container_name: bot
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/root/redis
    env_file:
      - .env

volumes:
  db_data:
  redis_data:
